/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biogranja.view;

import br.com.biogranja.control.controlCarregamentos;
import br.com.biogranja.control.controlFuncionarios;
import br.com.biogranja.control.controlGalinheiro;
import br.com.biogranja.model.AveCorte;
import br.com.biogranja.model.Aves;
import br.com.biogranja.model.Carga;
import br.com.biogranja.model.Funcionario;
import br.com.biogranja.model.GalinheiroCorte;
import br.com.biogranja.model.Gestor;
import java.awt.Color;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class viewInterno extends javax.swing.JFrame {
controlCarregamentos carga = new controlCarregamentos();
controlFuncionarios funcionarioDAO = new controlFuncionarios();
controlGalinheiro galinheiroDAO = new controlGalinheiro();
Gestor g;
int idcorte=0;
    /**
     * Creates new form viewInterno
     */
    public viewInterno() {
        initComponents();
        painelFunc.setVisible(false);
        painelGestor.setVisible(false);  
        panMoverCorte.setVisible(false);
        panMoverPostura.setVisible(false);
        inicializar();
    }
    
    public void inicializar(){
        Date dt = new Date();
        Funcionario f = new Funcionario(007,"Matheus Daltro",dt,"senha");
        funcionarioDAO.cadastrarFuncionario(f);
        g = new Gestor(10,"Adenilson Jamerson",dt,"senha");
        getContentPane().setBackground(Color.WHITE);
        GalinheiroCorte gc = new GalinheiroCorte(idcorte);
        idcorte++;
        Aves av = new Aves("Corte",4.300);
        AveCorte ave = new AveCorte(av);
        gc.addAve(ave);
        galinheiroDAO.cadastrarCorte(gc);
    }
    public String converterListaCarga(Aves lista[]){
        String txt="";
        int x=0; 
        while(lista[x]!=null){
            txt+=lista[x].toString()+"\n";
            x++;
        }
        return txt;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        painelFunc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNovaCarga = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtPesoNovaAve = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        scrPanListaCorte = new javax.swing.JScrollPane();
        txtListaCorte = new javax.swing.JTextArea();
        scrPanListaPostura = new javax.swing.JScrollPane();
        txtListaPostura = new javax.swing.JTextArea();
        btnNovaAveCorte = new javax.swing.JButton();
        btnNovaAvePostura = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtIDCarga = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnAtt = new javax.swing.JButton();
        btnFecharFunc = new javax.swing.JButton();
        painelGestor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnListarFunc = new javax.swing.JButton();
        btnCriarFunc = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnListarCorte = new javax.swing.JButton();
        btnCriarCorte = new javax.swing.JButton();
        btnExcluirFunc = new javax.swing.JButton();
        btnBuscarFunc = new javax.swing.JButton();
        txtFunc = new javax.swing.JTextField();
        btnExcluirCorte = new javax.swing.JButton();
        btnBuscarCorte = new javax.swing.JButton();
        txtGranjaCorte = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        btnMoverCorte = new javax.swing.JButton();
        panMoverCorte = new javax.swing.JPanel();
        btnConfirmarCorte = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        idCargaCorte = new javax.swing.JTextField();
        idGranjaCorte = new javax.swing.JTextField();
        btnMoverPostura = new javax.swing.JButton();
        panMoverPostura = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btnAddRacao = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        painelLogin = new javax.swing.JPanel();
        btnAccGest = new javax.swing.JButton();
        btnAccFunc = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        painelFunc.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Área de Funcionário");

        btnNovaCarga.setText("Nova Carga");
        btnNovaCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaCargaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Cadastro de ave");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setLabelFor(txtPesoNovaAve);
        jLabel10.setText("Peso");
        jLabel10.setToolTipText("");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtListaCorte.setColumns(20);
        txtListaCorte.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        txtListaCorte.setLineWrap(true);
        txtListaCorte.setRows(5);
        scrPanListaCorte.setViewportView(txtListaCorte);

        txtListaPostura.setColumns(20);
        txtListaPostura.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        txtListaPostura.setLineWrap(true);
        txtListaPostura.setRows(5);
        scrPanListaPostura.setViewportView(txtListaPostura);

        btnNovaAveCorte.setText("Corte");
        btnNovaAveCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaAveCorteActionPerformed(evt);
            }
        });

        btnNovaAvePostura.setText("Postura");
        btnNovaAvePostura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaAvePosturaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("ID Carga");

        txtIDCarga.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtIDCarga.setText("S/ID");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Aves de Corte");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Aves de Postura");

        btnAtt.setText("ATT");
        btnAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttActionPerformed(evt);
            }
        });

        btnFecharFunc.setText("Fechar Janela");
        btnFecharFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelFuncLayout = new javax.swing.GroupLayout(painelFunc);
        painelFunc.setLayout(painelFuncLayout);
        painelFuncLayout.setHorizontalGroup(
            painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFuncLayout.createSequentialGroup()
                .addGroup(painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFuncLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnNovaCarga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelFuncLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtIDCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel11))
                        .addGap(32, 32, 32))
                    .addGroup(painelFuncLayout.createSequentialGroup()
                        .addGroup(painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelFuncLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel9)
                                        .addComponent(txtPesoNovaAve, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnNovaAvePostura)
                                        .addComponent(btnNovaAveCorte))
                                    .addGap(23, 23, 23)))
                            .addGroup(painelFuncLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFecharFunc)
                                    .addComponent(jLabel1))))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFuncLayout.createSequentialGroup()
                        .addComponent(btnAtt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrPanListaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(scrPanListaPostura, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFuncLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(152, 152, 152)
                        .addComponent(jLabel13)
                        .addGap(91, 91, 91))))
        );
        painelFuncLayout.setVerticalGroup(
            painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel1))
                    .addComponent(jLabel13))
                .addGap(0, 0, 0)
                .addGroup(painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFuncLayout.createSequentialGroup()
                        .addGroup(painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelFuncLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(7, 7, 7)
                                .addComponent(txtIDCarga)
                                .addGap(0, 26, Short.MAX_VALUE))
                            .addComponent(btnNovaCarga, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFecharFunc)
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelFuncLayout.createSequentialGroup()
                                .addGroup(painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(btnAtt))
                                .addGroup(painelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelFuncLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(btnNovaAveCorte))
                                    .addGroup(painelFuncLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPesoNovaAve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(4, 4, 4))
                            .addComponent(btnNovaAvePostura))
                        .addContainerGap())
                    .addComponent(scrPanListaPostura, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrPanListaCorte)))
        );

        painelGestor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Gestor");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Funcionários");

        btnListarFunc.setText("Listar");
        btnListarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarFuncActionPerformed(evt);
            }
        });

        btnCriarFunc.setText("Criar");
        btnCriarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarFuncActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Granjas de Corte");

        btnListarCorte.setText("Lista Granjas");
        btnListarCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarCorteActionPerformed(evt);
            }
        });

        btnCriarCorte.setText("Criar Granja");
        btnCriarCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarCorteActionPerformed(evt);
            }
        });

        btnExcluirFunc.setText("Excluir ID");
        btnExcluirFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirFuncActionPerformed(evt);
            }
        });

        btnBuscarFunc.setText("Buscar ID");
        btnBuscarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFuncActionPerformed(evt);
            }
        });

        btnExcluirCorte.setText("Excluir Granja");
        btnExcluirCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCorteActionPerformed(evt);
            }
        });

        btnBuscarCorte.setText("Buscar Granja");
        btnBuscarCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCorteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Relatórios");

        jButton8.setText("Exibir Relatório");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Granjas de Postura");

        jButton13.setText("Lista Granjas");

        jButton14.setText("Excluir Granja");

        jButton15.setText("Buscar Granja");

        jButton16.setText("Criar Granja");

        btnMoverCorte.setText("Mover Cargas");
        btnMoverCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverCorteActionPerformed(evt);
            }
        });

        panMoverCorte.setBackground(new java.awt.Color(255, 255, 255));

        btnConfirmarCorte.setText("Mover");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Granja");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("ID Carga");

        javax.swing.GroupLayout panMoverCorteLayout = new javax.swing.GroupLayout(panMoverCorte);
        panMoverCorte.setLayout(panMoverCorteLayout);
        panMoverCorteLayout.setHorizontalGroup(
            panMoverCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMoverCorteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMoverCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMoverCorteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirmarCorte))
                    .addGroup(panMoverCorteLayout.createSequentialGroup()
                        .addGroup(panMoverCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panMoverCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idCargaCorte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idGranjaCorte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panMoverCorteLayout.setVerticalGroup(
            panMoverCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMoverCorteLayout.createSequentialGroup()
                .addGroup(panMoverCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCargaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMoverCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(idGranjaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmarCorte))
        );

        btnMoverPostura.setText("Mover Cargas");
        btnMoverPostura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverPosturaActionPerformed(evt);
            }
        });

        panMoverPostura.setBackground(new java.awt.Color(255, 255, 255));

        jButton17.setText("Mover");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Granja");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("ID Carga");

        javax.swing.GroupLayout panMoverPosturaLayout = new javax.swing.GroupLayout(panMoverPostura);
        panMoverPostura.setLayout(panMoverPosturaLayout);
        panMoverPosturaLayout.setHorizontalGroup(
            panMoverPosturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMoverPosturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMoverPosturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMoverPosturaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton17))
                    .addGroup(panMoverPosturaLayout.createSequentialGroup()
                        .addGroup(panMoverPosturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(panMoverPosturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panMoverPosturaLayout.setVerticalGroup(
            panMoverPosturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMoverPosturaLayout.createSequentialGroup()
                .addGroup(panMoverPosturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMoverPosturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton17))
        );

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnAddRacao.setText("Adicionar Ração");
        btnAddRacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelGestorLayout = new javax.swing.GroupLayout(painelGestor);
        painelGestor.setLayout(painelGestorLayout);
        painelGestorLayout.setHorizontalGroup(
            painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGestorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelGestorLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelGestorLayout.createSequentialGroup()
                        .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelGestorLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painelGestorLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBuscarFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCriarFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnListarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExcluirFunc)))
                            .addGroup(painelGestorLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8)
                                    .addGroup(painelGestorLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel5)))))
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelGestorLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(txtGranjaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelGestorLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnListarCorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnExcluirCorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMoverCorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddRacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panMoverCorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscarCorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCriarCorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(painelGestorLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelGestorLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelGestorLayout.createSequentialGroup()
                                        .addComponent(btnMoverPostura)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(panMoverPostura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelGestorLayout.createSequentialGroup()
                                        .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(painelGestorLayout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(painelGestorLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel14)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        painelGestorLayout.setVerticalGroup(
            painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGestorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addGroup(painelGestorLayout.createSequentialGroup()
                        .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelGestorLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton13)
                                    .addComponent(jButton16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton14)
                                    .addComponent(jButton15)))
                            .addGroup(painelGestorLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnListarFunc)
                                    .addComponent(btnCriarFunc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnBuscarFunc)
                                    .addComponent(btnExcluirFunc)))
                            .addGroup(painelGestorLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGranjaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnListarCorte)
                                    .addComponent(btnCriarCorte))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnExcluirCorte)
                                    .addComponent(btnBuscarCorte))))
                        .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelGestorLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(painelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMoverPostura)
                                    .addComponent(panMoverPostura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panMoverCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painelGestorLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8))
                            .addGroup(painelGestorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMoverCorte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddRacao))))
                    .addComponent(jSeparator5)))
        );

        painelLogin.setBackground(new java.awt.Color(255, 255, 255));

        btnAccGest.setText("Acesso Gestor");
        btnAccGest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccGestActionPerformed(evt);
            }
        });

        btnAccFunc.setText("Acesso Funcionário");
        btnAccFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccFuncActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("ID");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Senha");

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                        .addComponent(btnAccFunc)
                        .addGap(32, 32, 32)
                        .addComponent(btnAccGest))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGap(232, 232, 232))
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccGest)
                    .addComponent(btnAccFunc))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(painelFunc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelGestor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnAccGestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccGestActionPerformed
        String pass = new String (txtPass.getPassword());
        if (txtID.getText().equals(Integer.toString(g.getId())) && pass.equals(g.getSenha()))
        painelGestor.setVisible(true);
        else {
            JOptionPane.showMessageDialog(null, "Usuário ou senha inválida!"); 
        }
    }//GEN-LAST:event_btnAccGestActionPerformed

    private void btnAccFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccFuncActionPerformed
        if(funcionarioDAO.buscarFuncionario(Integer.parseInt(txtID.getText()))==null){
            JOptionPane.showMessageDialog(null, "Funcionário não cadastrado");
        } else {
        String pass = new String (txtPass.getPassword());
        Funcionario f = new Funcionario(funcionarioDAO.buscarFuncionario(Integer.parseInt(txtID.getText())));
        if (txtID.getText().equals(Integer.toString(f.getId())) && pass.equals(f.getSenha())) {
        painelFunc.setVisible(true);
        txtListaCorte.setEditable(false);
        txtListaPostura.setEditable(false);
        } else {
            JOptionPane.showMessageDialog(null, "Usuário ou senha inválida!"); 
            }
        }
    }//GEN-LAST:event_btnAccFuncActionPerformed

    private void btnNovaCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaCargaActionPerformed
        //txtListaCorte.setText(Integer.toString());
        Date dt = new Date();
        Carga cargtmp = new Carga(carga.geraID(),dt);
        carga.cadastrarCarga(cargtmp);
        txtIDCarga.setText(Integer.toString(cargtmp.getIdCarga()));
        txtListaCorte.setText("Lista vazia");
        txtListaPostura.setText("Lista vazia");
    }//GEN-LAST:event_btnNovaCargaActionPerformed

    private void btnAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttActionPerformed
        if(txtIDCarga.getText()!="S/ID"){
            if(txtListaCorte.getText().equals("Lista vazia")&&txtListaPostura.getText().equals("Lista vazia")){
                JOptionPane.showMessageDialog(null, "Carga Vazia !");
            }
        txtListaCorte.setText(converterListaCarga(carga.buscarCarga(Integer.parseInt(txtIDCarga.getText())).getListaCorte()));
        }
        else {
            JOptionPane.showMessageDialog(null, "Não há carga selecionada!");
        }
    }//GEN-LAST:event_btnAttActionPerformed

    private void btnNovaAveCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaAveCorteActionPerformed
        Aves avefenix = new Aves("Corte", Double.parseDouble(txtPesoNovaAve.getText()));
        carga.buscarCarga(Integer.parseInt(txtIDCarga.getText())).addListaCorte(avefenix);
        txtListaCorte.setText(converterListaCarga(carga.buscarCarga(Integer.parseInt(txtIDCarga.getText())).getListaCorte()));
    }//GEN-LAST:event_btnNovaAveCorteActionPerformed

    private void btnNovaAvePosturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaAvePosturaActionPerformed
        Aves avefenix = new Aves("Postura", Double.parseDouble(txtPesoNovaAve.getText()));
        carga.buscarCarga(Integer.parseInt(txtIDCarga.getText())).addListaPostura(avefenix);
        txtListaPostura.setText(converterListaCarga(carga.buscarCarga(Integer.parseInt(txtIDCarga.getText())).getListaPostura()));
    }//GEN-LAST:event_btnNovaAvePosturaActionPerformed

    private void btnFecharFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharFuncActionPerformed
        painelFunc.setVisible(false);
        txtIDCarga.setText("S/ID");
        txtListaCorte.setText("");
        txtListaPostura.setText("");
        txtPesoNovaAve.setText("");
    }//GEN-LAST:event_btnFecharFuncActionPerformed

    private void btnMoverCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverCorteActionPerformed
        if(panMoverCorte.isVisible()==false){
        panMoverCorte.setVisible(true);
        btnMoverCorte.setText("Fechar Painel");
        } else {
        panMoverCorte.setVisible(false);
        btnMoverCorte.setText("Mover Cargas"); 
        }
    }//GEN-LAST:event_btnMoverCorteActionPerformed

    private void btnMoverPosturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverPosturaActionPerformed
        if(panMoverPostura.isVisible()==false){
        panMoverPostura.setVisible(true);
        btnMoverPostura.setText("Fechar Painel");
        } else {
        panMoverPostura.setVisible(false);
        btnMoverPostura.setText("Mover Cargas"); 
        }
    }//GEN-LAST:event_btnMoverPosturaActionPerformed

    private void btnCriarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarFuncActionPerformed
        String s=JOptionPane.showInputDialog(null,"Digite o Nome");
        String p=JOptionPane.showInputDialog(null,"Digite a Senha");
        Date dt = new Date();
        Funcionario f = new Funcionario(random(),s,dt,p);
        funcionarioDAO.cadastrarFuncionario(f);
    }//GEN-LAST:event_btnCriarFuncActionPerformed

    private void btnListarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarFuncActionPerformed
    JOptionPane.showMessageDialog(null, funcionarioDAO.listarFuncionario());
    }//GEN-LAST:event_btnListarFuncActionPerformed

    private void btnBuscarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFuncActionPerformed
    if(funcionarioDAO.buscarFuncionario(Integer.parseInt(txtFunc.getText())) == null){
        JOptionPane.showMessageDialog(null, "Funcionário inexistente!");
    } else {
        JOptionPane.showMessageDialog(null, "Funcionário encontrado! \n"
                +funcionarioDAO.buscarFuncionario(Integer.parseInt(txtFunc.getText())).toString());
    }
    }//GEN-LAST:event_btnBuscarFuncActionPerformed

    private void btnExcluirFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFuncActionPerformed
        if(funcionarioDAO.removerFuncionario(funcionarioDAO.buscarFuncionario(Integer.parseInt(txtFunc.getText())))==true){
            JOptionPane.showMessageDialog(null, "Funcionário Removido !");
        } else {
            JOptionPane.showMessageDialog(null, "Funcionário não localizado !");
        }
    }//GEN-LAST:event_btnExcluirFuncActionPerformed

    private void btnExcluirCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCorteActionPerformed
        if(txtGranjaCorte.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Insira um ID!");
        } else {
        if(galinheiroDAO.removerCorte(galinheiroDAO.buscarCorte(Integer.parseInt(txtGranjaCorte.getText())))==true){
            JOptionPane.showMessageDialog(null, "Granja Removida !");
        } else {
            JOptionPane.showMessageDialog(null, "Granja não localizada !");
            }
        }
    }//GEN-LAST:event_btnExcluirCorteActionPerformed

    private void btnListarCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCorteActionPerformed
    JOptionPane.showMessageDialog(null, galinheiroDAO.listarCorte());
    }//GEN-LAST:event_btnListarCorteActionPerformed

    private void btnCriarCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarCorteActionPerformed
        GalinheiroCorte gc = new GalinheiroCorte(idcorte);
        idcorte++;
        galinheiroDAO.cadastrarCorte(gc);
    }//GEN-LAST:event_btnCriarCorteActionPerformed

    private void btnBuscarCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCorteActionPerformed
    if(galinheiroDAO.buscarCorte(Integer.parseInt(txtGranjaCorte.getText())) == null){
        JOptionPane.showMessageDialog(null, "Granja inexistente!");
    } else {
        JOptionPane.showMessageDialog(null, "Granja encontrada! \n"
                +galinheiroDAO.buscarCorte(Integer.parseInt(txtGranjaCorte.getText())).toString());
    }
    }//GEN-LAST:event_btnBuscarCorteActionPerformed

    private void btnAddRacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRacaoActionPerformed
    String s=JOptionPane.showInputDialog(null, "Digite a quantidade de ração (exemplo: 3.5 para 3,5Kg");
    double r = Double.parseDouble(s);
    if(galinheiroDAO.buscarCorte(Integer.parseInt(txtGranjaCorte.getText())) == null){
        JOptionPane.showMessageDialog(null, "Granja inexistente!");
    } else {
        GalinheiroCorte gc = galinheiroDAO.buscarCorte(Integer.parseInt(txtGranjaCorte.getText()));
        gc.setQtdRacao(r);
        galinheiroDAO.atualizarCorte(gc);
    }
    }//GEN-LAST:event_btnAddRacaoActionPerformed
    
    private int random(){
        Random random = new Random();
        return random.nextInt((999999 - 100000) + 1) + 100000;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewInterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewInterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewInterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewInterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewInterno().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccFunc;
    private javax.swing.JButton btnAccGest;
    private javax.swing.JButton btnAddRacao;
    private javax.swing.JButton btnAtt;
    private javax.swing.JButton btnBuscarCorte;
    private javax.swing.JButton btnBuscarFunc;
    private javax.swing.JButton btnConfirmarCorte;
    private javax.swing.JButton btnCriarCorte;
    private javax.swing.JButton btnCriarFunc;
    private javax.swing.JButton btnExcluirCorte;
    private javax.swing.JButton btnExcluirFunc;
    private javax.swing.JButton btnFecharFunc;
    private javax.swing.JButton btnListarCorte;
    private javax.swing.JButton btnListarFunc;
    private javax.swing.JButton btnMoverCorte;
    private javax.swing.JButton btnMoverPostura;
    private javax.swing.JButton btnNovaAveCorte;
    private javax.swing.JButton btnNovaAvePostura;
    private javax.swing.JButton btnNovaCarga;
    private javax.swing.JTextField idCargaCorte;
    private javax.swing.JTextField idGranjaCorte;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel painelFunc;
    private javax.swing.JPanel painelGestor;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JPanel panMoverCorte;
    private javax.swing.JPanel panMoverPostura;
    private javax.swing.JScrollPane scrPanListaCorte;
    private javax.swing.JScrollPane scrPanListaPostura;
    private javax.swing.JTextField txtFunc;
    private javax.swing.JTextField txtGranjaCorte;
    private javax.swing.JTextField txtID;
    private javax.swing.JLabel txtIDCarga;
    private javax.swing.JTextArea txtListaCorte;
    private javax.swing.JTextArea txtListaPostura;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtPesoNovaAve;
    // End of variables declaration//GEN-END:variables
}
